[tool.flake8]
ignore = ["W503, D100, D205, D401, F821, F403, F405"]
max-complexity = 10
line_length = 120

[tool.isort]
profile = "black"
line_length = 79
skip_glob = ["**/migrations/*.py"]
known_first_party = ["users,events,tickets"]
no_lines_before = "LOCALFORLDER"

[tool.black]
line-length = 79
target-version = ['py312']
